default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_DEVELOPMENT_NAME"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE_TEST_NAME"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_USERNAME"] %>
  username: <%= ENV["DATABASE_USERNAME_PRODUCTION"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
