default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: BookWorld_development

test:
  <<: *default
  database: BookWorld_test

production:
  <<: *default
  database: BookWorld_production
  username: BookWorld
  password: <%= ENV["DATABASE_PASSWORD"] %>
